<a href="https://colab.research.google.com/github/jan-podlipny/CS224n/blob/master/pytorch_warmup/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
from torch import nn
torch.manual_seed(18)

Sequential model

In [106]:
seq_model = nn.Sequential(nn.Linear(3,1),nn.Sigmoid())

print(list(seq_model.parameters()))
print(' ')
print(seq_model.state_dict())
state_dict = seq_model.state_dict()

[Parameter containing:
tensor([[ 0.5568, -0.4714, -0.5127]], requires_grad=True), Parameter containing:
tensor([0.5386], requires_grad=True)]
 
OrderedDict([('0.weight', tensor([[ 0.5568, -0.4714, -0.5127]])), ('0.bias', tensor([0.5386]))])


In [109]:
X = torch.tensor([1.,5.,20.])
yhat = seq_model(X)
print(yhat)

tensor([9.9789e-06], grad_fn=<SigmoidBackward>)


Custom class

In [110]:
class logistic_regression(nn.Module):
    
    # Constructor
    def __init__(self, n_inputs):
        super(logistic_regression, self).__init__()
        self.linear = nn.Linear(n_inputs, 1)
    
    # Prediction
    def forward(self, x):
        yhat = torch.sigmoid(self.linear(x))
        return yhat

In [124]:
model = logistic_regression(3)
print(model.state_dict())
c_state_dict = model.state_dict()
c_state_dict['linear.weight'], c_state_dict['linear.bias']  = state_dict['0.weight'],  state_dict['0.bias']
model.load_state_dict(c_state_dict)
print(model.state_dict())

OrderedDict([('linear.weight', tensor([[0.3853, 0.0116, 0.1424]])), ('linear.bias', tensor([0.3245]))])
OrderedDict([('linear.weight', tensor([[ 0.5568, -0.4714, -0.5127]])), ('linear.bias', tensor([0.5386]))])


In [125]:
yhat = model(X)
print("The prediction: ", yhat)

The prediction:  tensor([9.9789e-06], grad_fn=<SigmoidBackward>)
